spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://postgres:5432/company
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8080